### PR TITLE
Adapt imports for flutter_quill>3.4.4

### PR DESCRIPTION
**Pull request by devtud**

### CODE REVIEW

**Comment by WillowWisp** [comment]
`flutter_quill` just updated to 4.0.0, so I think we should change `flutter_quill: ^3.0.0` => `flutter_quill: ^4.0.0`

**Comment by devtud** [comment]
> `flutter_quill` just updated to 4.0.0, so I think we should change `flutter_quill: ^3.0.0` => `flutter_quill: ^4.0.0`

flutter_quill 4 requires flutter 2.10. I'm not sure delta_markdown has been tested against this flutter version

**Comment by dominikheeb** [comment]
> > `flutter_quill` just updated to 4.0.0, so I think we should change `flutter_quill: ^3.0.0` => `flutter_quill: ^4.0.0`
> 
> flutter_quill 4 requires flutter 2.10. I'm not sure delta_markdown has been tested against this flutter version

is there any progress or plans in testing for flutter 2.10? atm our project which is using your package is stuck at 2.5.2 since we can't update quill due to this package and for flutter 2.10 we need a new quill version.

**Comment by devtud** [comment]
> > > `flutter_quill` just updated to 4.0.0, so I think we should change `flutter_quill: ^3.0.0` => `flutter_quill: ^4.0.0`
> > 
> > 
> > flutter_quill 4 requires flutter 2.10. I'm not sure delta_markdown has been tested against this flutter version
> 
> is there any progress or plans in testing for flutter 2.10? atm our project which is using your package is stuck at 2.5.2 since we can't update quill due to this package and for flutter 2.10 we need a new quill version.

What I did was to create a branch on my fork in which I have as dependency flutter_quill ^4.0.0 and I use it as:

```yml
  delta_markdown:
    git:
      url: git://github.com/devtud/delta_markdown.git
      ref: flutter_quill_4
```
You can do the same until `delta_markdown` will officially push a version compatible with flutter_quill 4.

**Comment by dominikheeb** [comment]
> > > > `flutter_quill` just updated to 4.0.0, so I think we should change `flutter_quill: ^3.0.0` => `flutter_quill: ^4.0.0`
> > > 
> > > 
> > > flutter_quill 4 requires flutter 2.10. I'm not sure delta_markdown has been tested against this flutter version
> > 
> > 
> > is there any progress or plans in testing for flutter 2.10? atm our project which is using your package is stuck at 2.5.2 since we can't update quill due to this package and for flutter 2.10 we need a new quill version.
> 
> What I did was to create a branch on my fork in which I have as dependency flutter_quill ^4.0.0 and I use it as:
> 
> ```yaml
>   delta_markdown:
>     git:
>       url: git://github.com/devtud/delta_markdown.git
>       ref: flutter_quill_4
> ```
> 
> You can do the same until `delta_markdown` will officially push a version compatible with flutter_quill 4.

Ok thx for the tip
For us the issue is, we already make quite a stretch by using a not production ready package for our project and if we than have to rely on a fork somewhere the situation doesn't get better :)

Hopefully an official version compatible with flutter_quill 4 will follow soon :)

**Comment by dominikheeb** [comment]
Is there any update on this issue?

**Pull request merged**
